"""Модуль констант приложения."""
EMAIL_MAX_LENGTH = 254

NAME_MAX_LENGTH = 150

TAG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128

INGREDIENT_MEASURMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256

MIN_VALIDATOR_VALUE = 1

MAX_VALIDATOR_VALUE = 32767
