# Generated by Django 3.2.16 on 2024-09-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(auto_created=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
