# Generated by Django 3.2.16 on 2024-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
