# Generated by Django 3.2.16 on 2024-08-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240805_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribtion',
            new_name='subscription',
        ),
    ]
