# Generated by Django 3.2.16 on 2024-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240805_1654'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='unique_user_subscription'),
        ),
    ]
