# Generated by Django 3.2.16 on 2024-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.URLField(editable=False, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
