# Generated by Django 3.2.16 on 2024-08-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_subscription_unique_user_subscription'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_user_subscription',
        ),
    ]
