# Generated by Django 3.2.16 on 2024-08-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_subscription_unique_user_subscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'subscription'), name='unique_name_owner'),
        ),
    ]
