# Generated by Django 3.2.16 on 2024-08-15 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredientinrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Введенное количество меньше допустимого.')], verbose_name='Время приготовления'),
        ),
    ]
