# Generated by Django 3.2.16 on 2024-08-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_favorite_favorite_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='favorite_recipe',
            new_name='recipe',
        ),
    ]
