# Generated by Django 3.2.16 on 2024-08-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_auto_20240825_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'subscription')},
        ),
    ]
