# Generated by Django 3.2.16 on 2024-08-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'measurement_unit')},
        ),
    ]
